{% set name = "jupyterlab-quickopen" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_quickopen-{{ version }}.tar.gz
  sha256: b365aebaa4e06c717c15505d57ce05f754c9f870606e30f2427f60c4d6cb7c75

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version >=0.3.2
    - pip
  run:
    - python >={{ python_min }}
    - jupyter_server >=2.4.2,<3

test:
  imports:
    - jupyterlab_quickopen
  requires:
    - jupyterlab =4
    - pip
    - m2-grep  # [win]
    - python {{ python_min }}
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 2>&1 | grep -ie "jupyterlab-quickopen.*OK"
    - jupyter server extension list
    - jupyter server extension list 2>&1 | grep -ie "jupyterlab_quickopen.*OK"

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-quickopen
  summary: Quickly open a file in JupyterLab by part of its name
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jtpio
