{% set name = "jupyterlab-quickopen" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_quickopen-{{ version }}.tar.gz
  sha256: f8fb41c96d103aab0710a3710526432ed7a88658aeaf6b42719f7f13f6fe313c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version >=0.3.2
    - pip
  run:
    - python >=3.8
    - jupyter_server >=2.4.2,<3

test:
  imports:
    - jupyterlab_quickopen
  requires:
    - jupyterlab =4
    - pip
    - m2-grep  # [win]
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 2>&1 | grep -ie "jupyterlab-quickopen.*OK"
    - jupyter server extension list
    - jupyter server extension list 2>&1 | grep -ie "jupyterlab_quickopen.*OK"

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-quickopen
  summary: Quickly open a file in JupyterLab by part of its name
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jtpio
